spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.6/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
  undertow:
    io-threads: 16
    worker-threads: 256
    buffer-size: 1024
    direct-buffers: true
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:
#    path: /var/log/tomcat/sell
#  level:
#    com.imooc.sell.LoggerTest: debug

